## FRC Imports
from wpilib import SendableChooser, SmartDashboard, DriverStation
from wpimath.geometry import Rotation2d
from wpimath.units import rotationsToRadians

from commands2 import Command, cmd
from commands2.button import CommandXboxController, Trigger
from commands2.sysid import SysIdRoutine

from ntcore.util import ntproperty

# Hardware Lib Imports
from phoenix6 import swerve

## Local Imports
from commands import *
from subsystems import TunerConstants, Climber, Intake, Launcher, Agitator

from util import FalconXboxController, Telemetry, ControlMode

class RobotContainer:
    # Variable Declaration
    __autoChooser:SendableChooser = SendableChooser()

    def __init__(self) -> None:
        ### Controllers
        self.controller1 = FalconXboxController( 0 )
        self.controller2 = FalconXboxController( 1 )
        self.control_mode = ControlMode.TEST

        ### Subsystems
        ## Intake
        self.intakeSys = Intake( 10, 11, 0, -0.335205 )

        ## Agitator
        self.agitatorSys = Agitator( 12 )

        ## Launcher
        self.launcherSys = Launcher( 13 )

        ## Climber
        self.climbSys = Climber( 14 )

        ## Drive
        # self.swerveSys = TunerConstants.create_drivetrain() # TODO: Check configs
        # self._logger = Telemetry(TunerConstants.speed_at_12_volts)

        # Auto TODO: re-implement
        # self.__autoChooser.setDefaultOption( "1 - None", cmd.none() )
        # SmartDashboard.putData( "Autonomous Mode", self.__autoChooser )

        SmartDashboard.putData("Subsystems/Intake", self.intakeSys)
        SmartDashboard.putData("Subsystems/Agitator", self.agitatorSys)
        SmartDashboard.putData("Subsystems/Launcher", self.launcherSys)
        SmartDashboard.putData("Subsystems/Climber", self.climbSys)

        ### Configure the button bindings
        # self.configureDriveBindings()
        match self.control_mode:
            case ControlMode.COMP:
                self.configureCompBindings()
            case ControlMode.PRACTICE:
                self.configurePracticeBindings()
            case ControlMode.DEMO:
                self.configureDemoBindings()
            case ControlMode.TEST:
                self.configureTestBindings()

    def configureCompBindings(self) -> None:
        """
        configures controls for the robot at competition
        """
        ### Driver 1 (Driver)
        #NOTE: drive bindings handled in configureDriveBindings

        ### Driver 2 (Operator)
    def configurePracticeBindings(self) -> None:
        """
        configures controls for the robot in practice
        """
        ### Driver 1 (Driver)
        #NOTE: drive bindings handled in configureDriveBindings

        ### Driver 2 (Operator)
    def configureDemoBindings(self) -> None:
        """
        configures controls for the robot at demo
        """
        ### Driver 1 (Driver)
        #NOTE: drive bindings handled in configureDriveBindings

        ### Driver 2 (Operator)
    def configureTestBindings(self) -> None:
        """
        configures controls for the robot to test subsystems' functionality
        not for testing final bindings, put those in comp
        """
        #NOTE: drive bindings handled in configureDriveBindings
        ## Climbing
        # self.controller1.y().toggleOnTrue(ControlClimberPos(self.climbSys, self.controller1.getRightUpDown))

        ## Intaking
        # Pivot
        # self.controller1.a().toggleOnTrue(ControlPivotPos(self.climbSys, self.controller1.getRightUpDown))
        #OR
        # self.controller1.a().onTrue(PivotToPosition(self.intakeSys, Intake.IntakePositions.OUT))
        # self.controller1.b().onTrue(PivotToPosition(self.intakeSys, Intake.IntakePositions.IN))

        # bawlz
        self.controller1.x().toggleOnTrue(SetIntakeSpeed(self.intakeSys, Intake.IntakeSpeeds.IN))

        ## Launching
        # self.controller1.rightTrigger().whileTrue(RunLauncherByDist(self.launcherSys))
        # self.controller1.rightBumper().whileTrue(ControlFlywheelSpeed(self.agitatorSys, lambda: 3000))
        self.controller1.a().toggleOnTrue(RunFlyWheelByNT(self.launcherSys))
        self.controller1.b().toggleOnTrue(RunFlyWheelByNT(self.agitatorSys))
        # this is a stupid way to do waht its doing:
        self.controller1.rightTrigger(0.01).whileTrue(ControlFlywheelSpeed(self.launcherSys, self.controller1.getRightTriggerAxis))
        self.controller1.leftTrigger(0.01).whileTrue(ControlFlywheelSpeed(self.agitatorSys, self.controller1.getLeftTriggerAxis))

    # def configureDriveBindings(self) -> None:
    #     """
    #     Standard setup for basic drive controls

    #     current version auto-generated by phoenix6
    #     """

    #     self._max_speed = (
    #         1.0 * TunerConstants.speed_at_12_volts
    #     )  # speed_at_12_volts desired top speed
    #     self._max_angular_rate = rotationsToRadians(
    #         0.75
    #     )  # 3/4 of a rotation per second max angular velocity

    #     # Setting up bindings for necessary control of the swerve drive platform
    #     self._drive_req = (
    #         swerve.requests.FieldCentric()
    #         .with_deadband(self._max_speed * 0.1)
    #         .with_rotational_deadband(
    #             self._max_angular_rate * 0.1
    #         )  # Add a 10% deadband
    #         .with_drive_request_type(
    #             swerve.SwerveModule.DriveRequestType.OPEN_LOOP_VOLTAGE
    #         )  # Use open-loop control for drive motors
    #     )
    #     self._brake = swerve.requests.SwerveDriveBrake()
    #     self._point = swerve.requests.PointWheelsAt()

    #     # Note that X is defined as forward according to WPILib convention,
    #     # and Y is defined as to the left according to WPILib convention.
    #     self.swerveSys.setDefaultCommand(
    #         # Drivetrain will execute this command periodically
    #         self.swerveSys.apply_request(
    #             lambda: (
    #                 self._drive_req.with_velocity_x(
    #                     -self.controller1.getLeftY() * self._max_speed
    #                 )  # Drive forward with negative Y (forward)
    #                 .with_velocity_y(
    #                     -self.controller1.getLeftX() * self._max_speed
    #                 )  # Drive left with negative X (left)
    #                 .with_rotational_rate(
    #                     -self.controller1.getRightX() * self._max_angular_rate
    #                 )  # Drive counterclockwise with negative X (left)
    #             )
    #         )
    #     )

    #     # Idle while the robot is disabled. This ensures the configured
    #     # neutral mode is applied to the drive motors while disabled.
    #     idle = swerve.requests.Idle()
    #     Trigger(DriverStation.isDisabled).whileTrue(
    #         self.swerveSys.apply_request(lambda: idle).ignoringDisable(True)
    #     )

    #     self.controller1.a().whileTrue(self.swerveSys.apply_request(lambda: self._brake))
    #     self.controller1.b().whileTrue(
    #         self.swerveSys.apply_request(
    #             lambda: self._point.with_module_direction(
    #                 Rotation2d(-self.controller1.getLeftY(), -self.controller1.getLeftX())
    #             )
    #         )
    #     )

    #     # Run SysId routines when holding back/start and X/Y.
    #     # Note that each routine should be run exactly once in a single log.
    #     (self.controller1.back() & self.controller1.y()).whileTrue(
    #         self.swerveSys.sys_id_dynamic(SysIdRoutine.Direction.kForward)
    #     )
    #     (self.controller1.back() & self.controller1.x()).whileTrue(
    #         self.swerveSys.sys_id_dynamic(SysIdRoutine.Direction.kReverse)
    #     )
    #     (self.controller1.start() & self.controller1.y()).whileTrue(
    #         self.swerveSys.sys_id_quasistatic(SysIdRoutine.Direction.kForward)
    #     )
    #     (self.controller1.start() & self.controller1.x()).whileTrue(
    #         self.swerveSys.sys_id_quasistatic(SysIdRoutine.Direction.kReverse)
    #     )

    #     # reset the field-centric heading on left bumper press
    #     self.controller1.leftBumper().onTrue(
    #         self.swerveSys.runOnce(self.swerveSys.seed_field_centric)
    #     )

    #     self.swerveSys.register_telemetry(
    #         lambda state: self._logger.telemeterize(state)
    #     )

    # Get Autonomous Command
    def getAutonomousCommand(self) -> Command: pass
    #     """
    #     Use this to pass the autonomous command to the main {@link Robot} class.

    #     :returns: the command to run in autonomous

    #     current version auto-generated by phoenix6
    #     """
    #     # Simple drive forward auton
    #     idle = swerve.requests.Idle()
    #     return cmd.sequence(
    #         # Reset our field centric heading to match the robot
    #         # facing away from our alliance station wall (0 deg).
    #         self.swerveSys.runOnce(
    #             lambda: self.swerveSys.seed_field_centric(Rotation2d.fromDegrees(0))
    #         ),
    #         # Then slowly drive forward (away from us) for 5 seconds.
    #         self.swerveSys.apply_request(
    #             lambda: (
    #                 self._drive_req.with_velocity_x(0.5)
    #                 .with_velocity_y(0)
    #                 .with_rotational_rate(0)
    #             )
    #         )
    #         .withTimeout(5.0),
    #         # Finally idle for the rest of auton
    #         self.swerveSys.apply_request(lambda: idle)
    #     )
